### ISSUE TITLE
大佬,帮忙看下总是报这个错是什么问题

### ISSUE THREAD

**Issue by 717785320** [Peng-YM/QuanX#67]
PS C:\MITM> node "c:\MITM\Proxy.js"
Configuration loaded:
{"general":{"workspace":"/Rewrites","remote":""},"proxy":{"port":6789,"key":"mitmproxy.key.pem","cert":"mitmproxy.crt"},"mitm":["jd.com"],"scripts":[{"name":"test-request-body","type":"request","pattern":"*.jd.com","require_body":true,"path":"test-request-body.js","enabled":true}]}

Processing rewrites for Quantumult X...
Processing rewrites for Loon...
Processing rewrites for Surge...
Added script test-request-body.js
MITM proxy listenning on 6789...
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
?[90m    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)?[39m
Emitted 'error' event on Socket instance at:
?[90m    at emitErrorNT (internal/streams/destroy.js:84:8)?[39m
?[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)?[39m {
  errno: ?[33m-4077?[39m,
  code: ?[32m'ECONNRESET'?[39m,
  syscall: ?[32m'read'?[39m
}

**Comment by Peng-YM** [comment]
描述一下怎么出现的？
